name: cleanup
on: [workflow_dispatch]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: hugo
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
